Revert "Cvp 3377"

diff --git a/ci-operator/config/openshift-priv/cluster-api-provider-kubevirt/openshift-priv-cluster-api-provider-kubevirt-release-4.13.yaml b/ci-operator/config/openshift-priv/cluster-api-provider-kubevirt/openshift-priv-cluster-api-provider-kubevirt-release-4.13.yaml
--- a/ci-operator/config/openshift-priv/cluster-api-provider-kubevirt/openshift-priv-cluster-api-provider-kubevirt-release-4.13.yaml
+++ b/ci-operator/config/openshift-priv/cluster-api-provider-kubevirt/openshift-priv-cluster-api-provider-kubevirt-release-4.13.yaml
@@ -7,7 +7,7 @@ base_images:
     name: 4.13-priv
     namespace: ocp-private
     tag: cli
-  hypershift-operator-4.13:
+  hypershift-operator-4.11:
     name: 4.13-priv
     namespace: ocp-private
     tag: hypershift-operator
@@ -61,7 +61,7 @@ images:
     openshift_release_golang-1.18:
       as:
       - registry.ci.openshift.org/openshift/release:golang-1.18
-  to: cluster-api-provider-kubevirt
+  to: kubevirt-cluster-api-controllers
 - build_args:
   - name: ARCH
     value: amd64
@@ -96,8 +96,7 @@ images:
         git clone https://github.com/openshift/hypershift.git && \
         cd hypershift/ && \
         go mod tidy && go mod vendor && \
-        make e2e && \
-        sed -i 's|global-pull-secret.json|/tmp/global-pull-secret.json|g' ./hack/ci/install-cnv.sh
+        make e2e
     WORKDIR /go/src/github.com/openshift/hypershift
   from: src
   inputs:
@@ -105,7 +104,7 @@ images:
       paths:
       - destination_dir: .
         source_path: /usr/bin/oc
-    hypershift-operator-4.13:
+    hypershift-operator-4.11:
       paths:
       - destination_dir: .
         source_path: /usr/bin/hypershift
@@ -125,7 +124,7 @@ releases:
       product: ocp
       relative: 1
       stream: ci
-      version: "4.13"
+      version: "4.11"
   initial:
     integration:
       name: 4.13-priv
@@ -147,29 +146,104 @@ tests:
   commands: GOFLAGS="-mod=readonly" make test
   container:
     from: src
+- as: cluster-api-provider-kubevirt-e2e
+  steps:
+    cluster_profile: gcp
+    env:
+      SUB_CHANNEL: stable
+      SUB_INSTALL_NAMESPACE: openshift-cnv
+      SUB_PACKAGE: kubevirt-hyperconverged
+      SUB_TARGET_NAMESPACES: openshift-cnv
+    test:
+    - ref: operatorhub-subscribe
+    - as: deploy-cnv-hyperconverged-cr
+      commands: |-
+        oc create -f - <<EOF
+        apiVersion: hco.kubevirt.io/v1beta1
+        kind: HyperConverged
+        metadata:
+          name: kubevirt-hyperconverged
+          namespace: openshift-cnv
+        EOF
+
+        oc wait hyperconverged -n openshift-cnv kubevirt-hyperconverged --for=condition=Available --timeout=15m
+      from: capk-oc-bin-image
+      resources:
+        requests:
+          cpu: 500m
+          memory: 1Gi
+    - as: deploy-capk
+      commands: |-
+        set -x
+        # Deploy cluster API
+        cat <<EOF > clusterctl_config.yaml
+        cert-manager:
+          url: "https://github.com/cert-manager/cert-manager/releases/latest/cert-manager.yaml"
+        EOF
+
+        clusterctl init -v 4 --config=clusterctl_config.yaml
+
+        oc adm policy add-scc-to-user privileged system:serviceaccount:capk-system:capk-manager
+
+        export MANIFEST_IMG=${CAPK_IMAGE%:*}
+        export MANIFEST_TAG=${CAPK_IMAGE/*:}
+        GOFLAGS="-mod=readonly" make generate-manifests
+
+        sed -i -E "s|(^ +- image: ).*$|\1${CAPK_IMAGE}|" config/default/manager_image_patch.yaml
+
+        oc kustomize config/default | oc apply -f -
+        sleep 60
+
+        # Validate capk manager was created successfully
+        oc wait pod --for=condition=Ready -l cluster.x-k8s.io/provider=infrastructure-kubevirt -n capk-system --timeout=120s
+      dependencies:
+      - env: CAPK_IMAGE
+        name: kubevirt-cluster-api-controllers
+      from: capk-oc-bin-image
+      resources:
+        requests:
+          cpu: 500m
+          memory: 1Gi
+    - as: run-tests
+      commands: |-
+        set -x
+
+        export CRI_PATH=/var/run/crio/crio.sock
+        export IMAGE_REPO=k8s.gcr.io
+        export TENANT_CLUSTER_KUBERNETES_VERSION=v1.21.0
+        export NODE_VM_IMAGE_TEMPLATE=quay.io/kubevirtci/fedora-kubeadm:35
+
+        go version
+        go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo@latest
+        go mod tidy
+        GOFLAGS="-mod=readonly" ginkgo build e2e/
+        TESR_DIR=$(pwd)/test-dir
+        mkdir ${TESR_DIR}
+        e2e/e2e.test \
+          --kubectl-path=/usr/bin/oc \
+          --clusterctl-path=/usr/bin/clusterctl \
+          --working-dir=${TESR_DIR} \
+          --ginkgo.junit-report=${ARTIFACT_DIR}/junit_report.xml \
+          --ginkgo.label-filter="!persistentVMs" \
+          --ginkgo.skip="unrecoverable VMI"
+      from: capk-oc-bin-image
+      resources:
+        requests:
+          cpu: 500m
+          memory: 1Gi
+    workflow: ipi-gcp
 - as: cluster-api-provider-kubevirt-with-hypershift
   steps:
-    cluster_profile: aws-virtualization
-    env:
-      BASE_DOMAIN: cnv-ci.syseng.devcluster.openshift.com
-      COMPUTE_NODE_REPLICAS: "1"
-      COMPUTE_NODE_TYPE: c5n.metal
-      CONTROL_PLANE_INSTANCE_TYPE: m4.xlarge
+    cluster_profile: gcp
     test:
     - as: deploy-cnv
-      cli: latest
-      commands: CNV_PRERELEASE_VERSION=4.13 ./hack/ci/install-cnv.sh
-      credentials:
-      - mount_path: /etc/cnv-nightly-pull-credentials
-        name: openshift-cnv-quay-credentials
-        namespace: test-credentials
+      commands: ./hack/ci/install-cnv.sh
       from: hypershift-cli-e2e
       resources:
         requests:
           cpu: 500m
           memory: 1Gi
     - as: deploy-hypershift
-      cli: latest
       commands: |-
         set -x
         hypershift install
@@ -178,28 +252,50 @@ tests:
         # make sure the patch worked
         oc get deployment -n hypershift operator -o yaml | grep "${CAPK_IMAGE}"
 
-        oc rollout status deployment -n hypershift operator --timeout=5m
+        VALID_IMAGE="false"
+        # verify the image in the manager pod
+        for i in $(seq 20); do
+          sleep 60
+          # wait until the old pod is deleted
+          if [[ $(oc get pods -n hypershift -l "app=operator,hypershift.openshift.io/operator-component=operator,name=operator" --no-headers | wc -l) != 1 ]]; then
+            continue
+          fi
+          # check if the pod contains the required env var
+          if [[ $(oc get pods -n hypershift -l "app=operator,hypershift.openshift.io/operator-component=operator,name=operator" -o yaml | grep "name: IMAGE_KUBEVIRT_CAPI_PROVIDER" -A1 | grep "value: ${CAPK_IMAGE}") ]]; then
+            VALID_IMAGE=true
+            break
+          fi
+        done
+
+        if [[ "${VALID_IMAGE}" == "true" ]]; then
+          oc wait deployment -n hypershift operator --for=condition=Available --timeout=5m
+        else
+          echo "error: couldn't validate the manager pod image."
+          exit 1
+        fi
       dependencies:
       - env: CAPK_IMAGE
-        name: cluster-api-provider-kubevirt
+        name: kubevirt-cluster-api-controllers
       from: hypershift-cli-e2e
       resources:
         requests:
           cpu: 500m
           memory: 1Gi
     - as: hypershift-e2e
-      cli: latest
       commands: |-
-        set -ex
+        set -x
+        export KUBEVIRT_PLATFORM_ENABLED=true
+
         # run the test
         bin/test-e2e \
                   --test.v \
                   --test.timeout=0 \
-                  --test.run='^TestCreateCluster$' \
+                  --test.run=TestKubeVirtCreateCluster \
                   --e2e.latest-release-image=${OCP_IMAGE_LATEST} \
                   --e2e.previous-release-image=${OCP_IMAGE_PREVIOUS} \
                   --e2e.node-pool-replicas=2 \
                   --e2e.kubevirt-node-memory="6Gi" \
+                  --e2e.base-domain="fake" \
                   --e2e.pull-secret-file=/etc/ci-pull-credentials/.dockerconfigjson \
                   --e2e.platform=KubeVirt
       credentials:
@@ -216,7 +312,7 @@ tests:
         requests:
           cpu: 500m
           memory: 1Gi
-    workflow: ipi-aws-ovn
+    workflow: ipi-gcp-ovn
 zz_generated_metadata:
   branch: release-4.13
   org: openshift-priv
